# Change these first
owner: tingelmar # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: "1122"
    url: https://1122.com.uy/
  - name: "BuscoInfo"
    url: https://buscoinfo.com.py/
  - name: "Tingelmar"
    url: https://www.tingelmar.com/
  - name: "Business API"
    url: "https://www.tingelmar.com/com/app/api.php?piid=LOC197190001&opts=GQ&html=1&prm=1&rel=1&subs=1&id=5fc525278fc65&action=gmpiid2"
  - name: "Video API"
    url: "https://video.bambus.tech/api/organization/ping"
  - name: "Booking API"
    url: "https://booking.bambus.tech/api/organization/ping"
    
assignees:
  - i5o
  - Rondeus

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  cname: status.tingelmar.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tingelmar
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
