# Change these first
owner: tingelmar # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: "1122"
    url: https://1122.com.uy/
  - name: "BuscoInfo"
    url: https://buscoinfo.com.py/
  - name: "Tingelmar"
    url: https://www.tingelmar.com/

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  cname: status.bambus.tech
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
